module.exports = {

	// Triggers the instructions menu that shares the video
	HOW_TO_PLAY: 'HOW_TO_PLAY',
	PRIZES: 'PRIZES',

	// Start the summer adventure
	BEGIN_ADVENTURE: 'BEGIN_ADVENTURE',

	SCAN_STAMP: 'SCAN_STAMP',
	CHECK_PROGRESS: 'CHECK_PROGRESS',
	OPPORTUNITIES: 'OPPORTUNITIES',
	ABOUT_SUMMER_ADVENTURE: 'ABOUT_SUMMER_ADVENTURE',
	ABOUT_CMOA: 'ABOUT_CMOA',
	ABOUT_CMNH: 'ABOUT_CMNH',
	ABOUT_WARHOL: 'ABOUT_WARHOL',
	ABOUT_MEMBERSHIP: 'ABOUT_MEMBERSHIP'
};
