module.exports = {
    SCAN_STAMP: 'SCAN_STAMP',
    CHECK_PROGRESS: 'CHECK_PROGRESS',
    OPPORTUNITIES: 'OPPORTUNITIES',
    ABOUT_SUMMER_ADVENTURE: "ABOUT_SUMMER_ADVENTURE",
    ABOUT_CMOA: 'ABOUT_CMOA',
    ABOUT_CMNH: 'ABOUT_CMNH',
    ABOUT_WARHOL: 'ABOUT_WARHOL',
    ABOUT_MEMBERSHIP: 'ABOUT_MEMBERSHIP'
}